name: Run ETL Pipeline

on:
  workflow_dispatch:  # Menambahkan trigger manual
  schedule:
    - cron: '*/30 * * * *'  # Jalankan setiap hari pukul 06:00 UTC

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt
   
    - name: Decode Google Cloud Credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > service_account_key.json
    
    - name: Set Environment Variable
      # Menentukan path ke file JSON sebagai Default Credentials
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/service_account_key.json" >> $GITHUB_ENV

    - name: Debug - Check Environment Variable
      run: echo $GOOGLE_APPLICATION_CREDENTIALS

    - name: Run ETL Pipeline
      run: python main.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data_saham.csv latest_data_saham.csv
        git commit -m "Update data_saham.csv and latest_data_saham.csv"
        git push


    
